-- custom fields

INSERT INTO "customFieldTable" ("table", "name", "module") 
VALUES 
('account', 'Account', 'Accounting'),
('accountCategory', 'Account Category', 'Accounting'),
('accountSubcategory', 'Account Subcategory', 'Accounting'),
('contractor', 'Contractor', 'Resources'),
('currency', 'Currency', 'Accounting'),
('customer', 'Customer', 'Sales'),
('customerContact', 'Customer Contact', 'Sales'),
('customerLocation', 'Customer Location', 'Sales'),
('customerStatus', 'Customer Status', 'Sales'),
('customerType', 'Customer Type', 'Sales'),
('department', 'Department', 'Resources'),
('employeeJob', 'Employee Job', 'Resources'),
('equipment', 'Equipment', 'Resources'),
('equipmentType', 'Equipment Type', 'Resources'),
('holiday', 'Holiday', 'Resources'),
('journal', 'Journal', 'Accounting'),
('journalLine', 'Journal Line', 'Accounting'),
('location', 'Location', 'Resources'),
('part', 'Part', 'Parts'),
('partCost', 'Part Cost', 'Parts'),
('partGroup', 'Part Group', 'Parts'),
('partInventory', 'Part Inventory', 'Parts'),
('partPlanning', 'Part Planning', 'Parts'),
('partReplenishment', 'Part Replenishment', 'Parts'),
('partSupplier', 'Part Supplier', 'Parts'),
('partUnitSalePrice', 'Part Unit Sale Price', 'Parts'),
('partner', 'Partner', 'Resources'),
('paymentTerm', 'Payment Term', 'Accounting'),
('purchaseInvoice', 'Purchase Invoice', 'Invoicing'),
('purchaseInvoiceLine', 'Purchase Invoice Line', 'Invoicing'),
('purchasePayment', 'Purchase Invoice Payment', 'Invoicing'),
('purchaseOrder', 'Purchase Order', 'Purchasing'),
('purchaseOrderDelivery', 'Purchase Order Delivery', 'Purchasing'),
('purchaseOrderLine', 'Purchase Order Line', 'Purchasing'),
('purchaseOrderPayment', 'Purchase Order Payment', 'Purchasing'),
('quote', 'Quote', 'Sales'),
('quoteAssembly', 'Quote Assembly', 'Sales'),
('quoteLine', 'Quote Line', 'Sales'),
('quoteMaterial', 'Quote Material', 'Sales'),
('quoteOperation', 'Quote Operation', 'Sales'),
('receipt', 'Receipt', 'Inventory'),
('requestForQuote', 'RFQ', 'Purchasing'),
('requestForQuoteLine', 'RFQ Line', 'Purchasing'),
('requestForQuoteSupplier', 'RFQ Supplier', 'Purchasing'),
('service', 'Service', 'Parts'),
('serviceSupplier', 'Service Supplier', 'Parts'),
('shelf', 'Shelf', 'Inventory'),
('shift', 'Shift', 'Resources'),
('shippingMethod', 'Shipping Method', 'Inventory'),
('shippingTerm', 'Shipping Term', 'Accounting'),
('supplier', 'Supplier', 'Purchasing'),
('supplierContact', 'Supplier Contact', 'Purchasing'),
('supplierLocation', 'Supplier Location', 'Purchasing'),
('supplierPayment', 'Supplier Payment', 'Purchasing'),
('supplierShipping', 'Supplier Shipping', 'Purchasing'),
('supplierStatus', 'Supplier Status', 'Purchasing'),
('supplierType', 'Supplier Type', 'Purchasing'),
('unitOfMeasure', 'Unit of Measure', 'Inventory'),
('workCell', 'Work Cell', 'Resources'),
('workCellType', 'Work Cell Type', 'Resources');

-- currencies

INSERT INTO "currency" ("name", "code", "symbol", "exchangeRate", "decimalPlaces", "isBaseCurrency", "createdBy") 
VALUES ('US Dollar', 'USD', '$', 1, 2, TRUE, 'system'),
	('Canadian Dollar', 'CAD', 'CA$', 1, 2, FALSE, 'system'),
	('Euro', 'EUR', '€', 1, 2, FALSE, 'system'),
	('United Arab Emirates Dirham', 'AED', 'AED', 1, 2, FALSE, 'system'),
	('Afghan Afghani', 'AFN', 'Af', 1, 0, FALSE, 'system'),
	('Albanian Lek', 'ALL', 'ALL', 1, 0, FALSE, 'system'),
	('Armenian Dram', 'AMD', 'AMD', 1, 0, FALSE, 'system'),
	('Argentine Peso', 'ARS', 'AR$', 1, 2, FALSE, 'system'),
	('Australian Dollar', 'AUD', 'AU$', 1, 2, FALSE, 'system'),
	('Azerbaijani Manat', 'AZN', 'man.', 1, 2, FALSE, 'system'),
	('Bosnia-Herzegovina Convertible Mark', 'BAM', 'KM', 1, 2, FALSE, 'system'),
	('Bangladeshi Taka', 'BDT', 'Tk', 1, 2, FALSE, 'system'),
	('Bulgarian Lev', 'BGN', 'BGN', 1, 2, FALSE, 'system'),
	('Bahraini Dinar', 'BHD', 'BD', 1, 3, FALSE, 'system'),
	('Burundian Franc', 'BIF', 'FBu', 1, 0, FALSE, 'system'),
	('Brunei Dollar', 'BND', 'BN$', 1, 2, FALSE, 'system'),
	('Bolivian Boliviano', 'BOB', 'Bs', 1, 2, FALSE, 'system'),
	('Brazilian Real', 'BRL', 'R$', 1, 2, FALSE, 'system'),
	('Botswanan Pula', 'BWP', 'BWP', 1, 2, FALSE, 'system'),
	('Belarusian Ruble', 'BYN', 'Br', 1, 2, FALSE, 'system'),
	('Belize Dollar', 'BZD', 'BZ$', 1, 2, FALSE, 'system'),
	('Congolese Franc', 'CDF', 'CDF', 1, 2, FALSE, 'system'),
	('Swiss Franc', 'CHF', 'CHF', 1, 2, FALSE, 'system'),
	('Chilean Peso', 'CLP', 'CL$', 1, 0, FALSE, 'system'),
	('Chinese Yuan', 'CNY', 'CN¥', 1, 2, FALSE, 'system'),
	('Colombian Peso', 'COP', 'CO$', 1, 0, FALSE, 'system'),
	('Costa Rican Colón', 'CRC', '₡', 1, 0, FALSE, 'system'),
	('Cape Verdean Escudo', 'CVE', 'CV$', 1, 2, FALSE, 'system'),
	('Czech Republic Koruna', 'CZK', 'Kč', 1, 2, FALSE, 'system'),
	('Djiboutian Franc', 'DJF', 'Fdj', 1, 0, FALSE, 'system'),
	('Danish Krone', 'DKK', 'Dkr', 1, 2, FALSE, 'system'),
	('Dominican Peso', 'DOP', 'RD$', 1, 2, FALSE, 'system'),
	('Algerian Dinar', 'DZD', 'DA', 1, 2, FALSE, 'system'),
	('Egyptian Pound', 'EGP', 'EGP', 1, 2, FALSE, 'system'),
	('Eritrean Nakfa', 'ERN', 'Nfk', 1, 2, FALSE, 'system'),
	('Ethiopian Birr', 'ETB', 'Br', 1, 2, FALSE, 'system'),
	('British Pound Sterling', 'GBP', '£', 1, 2, FALSE, 'system'),
	('Georgian Lari', 'GEL', 'GEL', 1, 2, FALSE, 'system'),
	('Ghanaian Cedi', 'GHS', 'GH₵', 1, 2, FALSE, 'system'),
	('Guinean Franc', 'GNF', 'FG', 1, 0, FALSE, 'system'),
	('Guatemalan Quetzal', 'GTQ', 'GTQ', 1, 2, FALSE, 'system'),
	('Hong Kong Dollar', 'HKD', 'HK$', 1, 2, FALSE, 'system'),
	('Honduran Lempira', 'HNL', 'HNL', 1, 2, FALSE, 'system'),
	('Croatian Kuna', 'HRK', 'kn', 1, 2, FALSE, 'system'),
	('Hungarian Forint', 'HUF', 'Ft', 1, 0, FALSE, 'system'),
	('Indonesian Rupiah', 'IDR', 'Rp', 1, 0, FALSE, 'system'),
	('Israeli New Sheqel', 'ILS', '₪', 1, 2, FALSE, 'system'),
	('Indian Rupee', 'INR', 'Rs', 1, 2, FALSE, 'system'),
	('Iraqi Dinar', 'IQD', 'IQD', 1, 0, FALSE, 'system'),
	('Iranian Rial', 'IRR', 'IRR', 1, 0, FALSE, 'system'),
	('Icelandic Króna', 'ISK', 'Ikr', 1, 0, FALSE, 'system'),
	('Jamaican Dollar', 'JMD', 'J$', 1, 2, FALSE, 'system'),
	('Jordanian Dinar', 'JOD', 'JD', 1, 3, FALSE, 'system'),
	('Japanese Yen', 'JPY', '¥', 1, 0, FALSE, 'system'),
	('Kenyan Shilling', 'KES', 'Ksh', 1, 2, FALSE, 'system'),
	('Cambodian Riel', 'KHR', 'KHR', 1, 2, FALSE, 'system'),
	('Comorian Franc', 'KMF', 'CF', 1, 0, FALSE, 'system'),
	('South Korean Won', 'KRW', '₩', 1, 0, FALSE, 'system'),
	('Kuwaiti Dinar', 'KWD', 'KD', 1, 3, FALSE, 'system'),
	('Kazakhstani Tenge', 'KZT', 'KZT', 1, 2, FALSE, 'system'),
	('Lebanese Pound', 'LBP', 'L.L.', 1, 0, FALSE, 'system'),
	('Sri Lankan Rupee', 'LKR', 'SLRs', 1, 2, FALSE, 'system'),
	('Lithuanian Litas', 'LTL', 'Lt', 1, 2, FALSE, 'system'),
	('Latvian Lats', 'LVL', 'Ls', 1, 2, FALSE, 'system'),
	('Libyan Dinar', 'LYD', 'LD', 1, 3, FALSE, 'system'),
	('Moroccan Dirham', 'MAD', 'MAD', 1, 2, FALSE, 'system'),
	('Moldovan Leu', 'MDL', 'MDL', 1, 2, FALSE, 'system'),
	('Malagasy Ariary', 'MGA', 'MGA', 1, 0, FALSE, 'system'),
	('Macedonian Denar', 'MKD', 'MKD', 1, 2, FALSE, 'system'),
	('Myanma Kyat', 'MMK', 'MMK', 1, 0, FALSE, 'system'),
	('Macanese Pataca', 'MOP', 'MOP$', 1, 2, FALSE, 'system'),
	('Mauritian Rupee', 'MUR', 'MURs', 1, 0, FALSE, 'system'),
	('Mexican Peso', 'MXN', 'MX$', 1, 2, FALSE, 'system'),
	('Malaysian Ringgit', 'MYR', 'RM', 1, 2, FALSE, 'system'),
	('Mozambican Metical', 'MZN', 'MTn', 1, 2, FALSE, 'system'),
	('Namibian Dollar', 'NAD', 'N$', 1, 2, FALSE, 'system'),
	('Nigerian Naira', 'NGN', '₦', 1, 2, FALSE, 'system'),
	('Nicaraguan Córdoba', 'NIO', 'C$', 1, 2, FALSE, 'system'),
	('Norwegian Krone', 'NOK', 'Nkr', 1, 2, FALSE, 'system'),
	('Nepalese Rupee', 'NPR', 'NPRs', 1, 2, FALSE, 'system'),
	('New Zealand Dollar', 'NZD', 'NZ$', 1, 2, FALSE, 'system'),
	('Omani Rial', 'OMR', 'OMR', 1, 3, FALSE, 'system'),
	('Panamanian Balboa', 'PAB', 'B/.', 1, 2, FALSE, 'system'),
	('Peruvian Nuevo Sol', 'PEN', 'S/.', 1, 2, FALSE, 'system'),
	('Philippine Peso', 'PHP', '₱', 1, 2, FALSE, 'system'),
	('Pakistani Rupee', 'PKR', 'PKRs', 1, 0, FALSE, 'system'),
	('Polish Zloty', 'PLN', 'zł', 1, 2, FALSE, 'system'),
	('Paraguayan Guarani', 'PYG', '₲', 1, 0, FALSE, 'system'),
	('Qatari Rial', 'QAR', 'QR', 1, 2, FALSE, 'system'),
	('Romanian Leu', 'RON', 'RON', 1, 2, FALSE, 'system'),
	('Serbian Dinar', 'RSD', 'din.', 1, 0, FALSE, 'system'),
	('Russian Ruble', 'RUB', 'RUB', 1, 2, FALSE, 'system'),
	('Rwandan Franc', 'RWF', 'RWF', 1, 0, FALSE, 'system'),
	('Saudi Riyal', 'SAR', 'SR', 1, 2, FALSE, 'system'),
	('Sudanese Pound', 'SDG', 'SDG', 1, 2, FALSE, 'system'),
	('Swedish Krona', 'SEK', 'Skr', 1, 2, FALSE, 'system'),
	('Singapore Dollar', 'SGD', 'S$', 1, 2, FALSE, 'system'),
	('Somali Shilling', 'SOS', 'Ssh', 1, 0, FALSE, 'system'),
	('Syrian Pound', 'SYP', 'SY£', 1, 0, FALSE, 'system'),
	('Thai Baht', 'THB', '฿', 1, 2, FALSE, 'system'),
	('Tunisian Dinar', 'TND', 'DT', 1, 3, FALSE, 'system'),
	('Tongan Paʻanga', 'TOP', 'T$', 1, 2, FALSE, 'system'),
	('Turkish Lira', 'TRY', 'TL', 1, 2, FALSE, 'system'),
	('Trinidad and Tobago Dollar', 'TTD', 'TT$', 1, 2, FALSE, 'system'),
	('New Taiwan Dollar', 'TWD', 'NT$', 1, 2, FALSE, 'system'),
	('Tanzanian Shilling', 'TZS', 'TSh', 1, 0, FALSE, 'system'),
	('Ukrainian Hryvnia', 'UAH', '₴', 1, 2, FALSE, 'system'),
	('Ugandan Shilling', 'UGX', 'USh', 1, 0, FALSE, 'system'),
	('Uruguayan Peso', 'UYU', '$U', 1, 2, FALSE, 'system'),
	('Uzbekistan Som', 'UZS', 'UZS', 1, 0, FALSE, 'system'),
	('Venezuelan Bolívar', 'VEF', 'Bs.F.', 1, 2, FALSE, 'system'),
	('Vietnamese Dong', 'VND', '₫', 1, 0, FALSE, 'system'),
	('CFA Franc BEAC', 'XAF', 'FCFA', 1, 0, FALSE, 'system'),
	('CFA Franc BCEAO', 'XOF', 'CFA', 1, 0, FALSE, 'system'),
	('Yemeni Rial', 'YER', 'YR', 1, 0, FALSE, 'system'),
	('South African Rand', 'ZAR', 'R', 1, 2, FALSE, 'system'),
	('Zambian Kwacha', 'ZMK', 'ZK', 1, 0, FALSE, 'system'),
	('Zimbabwean Dollar', 'ZWL', 'ZWL$', 1, 0, FALSE, 'system');